apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-deployment
  namespace: staging
  labels:
    app: identity-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: identity-app
  template:
    metadata:
      labels:
        app: identity-app
    spec:
      containers:
      - name: identity-app
        image: fclebinho/authorize-api:latest
        ports:
        - containerPort: 8082
        envFrom:
        - secretRef:
            name: identity-provider-env