apiVersion: apps/v1
kind: Deployment
metadata:
  name: wallet-deployment
  namespace: staging
  labels:
    app: wallet-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wallet-app
  template:
    metadata:
      labels:
        app: wallet-app
    spec:
      containers:
      - name: wallet-app
        image: gomesdevelop/wallet-api:latest
        ports:
        - containerPort: 8080
        envFrom:
        - secretRef:
            name: wallet-env