apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: production-nginx-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/gomesdevelop/gomesdevops.git
    targetRevision: HEAD
    path: apps/production/nginx
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true