apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: staging-letsencrypt
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/gomesdevelop/gomesdevops.git
    targetRevision: HEAD
    path: apps/staging/letsencrypt
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true