apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: staging-ingress
  namespace: staging
  annotations:
    cert-manager.io/cluster-issuer: "staging-letsencrypt"
spec:
  tls:
  - hosts:
    - "staging.gomes.dev"
    secretName: app-letsencrypt-cert
  - hosts:
    - "api.staging.gomes.dev"
    secretName: api-letsencrypt-cert
  ingressClassName: nginx
  rules:
  - host: staging.gomes.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-service
            port:
              number: 80
  - host: api.staging.gomes.dev
    http:
      paths:
      - path: /auth
        pathType: Prefix
        backend:
          service:
            name: identity-svc
            port:
              number: 8082
      - path: /wallet
        pathType: Prefix
        backend:
          service:
            name: wallet-svc
            port:
              number: 8080
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-service
            port:
              number: 80