apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: staging-ingress
  namespace: staging
  annotations:
    cert-manager.io/issuer: "letsencrypt-staging"
    ngninx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - api.staging.plussoftware.com.br
    secretName: letsencrypt-staging-tls
  rules:
  - host: api.staging.plussoftware.com.br
    http:
      paths:
      - path: /auth
        pathType: Prefix
        backend:
          service:
            name: identity-svc
            port:
              number: 8080