apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: production-ingress
  namespace: argocd
  annotations:
    cert-manager.io/cluster-issuer: "production-letsencrypt"
spec:
  ingressClassName: nginx
  rules:
  - host: argocd.kub3.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: argocd-server
            port:
              name: https
  tls:
  - hosts:
    - "argocd.kub3.dev"
    secretName: argocd-letsencrypt-cert